### PR TITLE
Remove runserver

### PR DESCRIPTION
**Pull request by crazcalm**
squashed commit

This replaces #262.

### CODE REVIEW

**Comment by crazcalm** [comment]
Wait, I sqaushed the commits that I made for the runserver changes. Did you want me to squash the merge commits as well?

**Comment by dirn** [comment]
It looks like you created pull requests to get changed from this repository into your fork. That's an awkward workflow that's going to lead to a gnarly commit history. The commits need to be squashed and we need to help you find a better workflow to avoid them in the future.

**Comment by dirn** [comment]
It also looks like you closed your original pull request and opened a new one. You should have updated the original. New ones should only be created when your branch has fallen so far behind master it can't be rebased cleanly.

**Comment by crazcalm** [comment]
I think my awkward git workflow has ruined this branch.

On the original branch, after I squashed two of the commits, I was no longer able to push my local branch to github. This was because there were no new changes to push. I then delete that github branch so that I could push my new local branch.

Now I have added the pygotham repo as a remote, pulled master, rebased the remover_runserver branch with master, which seemed to give me the desired result of not having all of those merge commits. However, my local branch is now behind the github branch and, as a result, I cannot push my local remover_runserver branch to github.

I created a new branch called remove_runserver2 so that you guys can see it. Does that branch have the desired clean history?

In terms of next steps, what should I do?

**Comment by dirn** [comment]
When you change a branch's history, you have to do a force push to any remote that needs the updated branch (if it had a copy of the old history). While you don't want to force push master, it's pretty common to do so with feature branches in a rebase-based workflow.

**Comment by crazcalm** [comment]
I forced pushed the my local branch.

What do you mean by "restore the shell command"?

**Comment by dirn** [comment]
See @jonafato's comment in #262. (This is why it's important not to close and open a duplicate pull request unless it's absolutely necessary.)

**Comment by crazcalm** [comment]
Sorry about all the confusion. The shell command is back.

**Comment by jonafato** [comment]
Looks good to me! :+1:

**Pull request merged**
